/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tiko (https://sketchfab.com/tikoavp)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bitcoin-logo-4c4d85419c924df4abfb83a76ddd3d42
title: Bitcoin Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bitt.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={1}>
            <mesh geometry={nodes.Bitcoin_Logo__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bitt.gltf')
